config/routes.rb
Rails.application.routes.draw do
  resources :notes
  get '/event_calendar/calendar/(:date)', to: 'event_calendar#calendar', as: 'event_calendar'
  get '/event_calendar/full_year_calendar/(:date)', to: 'event_calendar#full_year_calendar', as: 'full_year_calendar'

  resources :events
  devise_for :users
  root to: 'static_pages#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :content)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= simple_form_for(@note) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= tinymce_assets %>
<%= tinymce %>

app/views/notes/edit.html.erb
<div class="container">
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>
</div>

app/views/notes/index.html.erb
<div class="container">
  <h1>Notes</h1>
  <% @notes.order(:created_at).reverse_order.each do |note| %>
    <hr />
    <%= link_to "#{note.title} - #{note.created_at}", note_path(note) %> - <%= link_to 'Edit', edit_note_path(note) %> - <%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
  <hr />
  <%= link_to 'New Note', new_note_path %>
</div>

app/views/notes/new.html.erb
<div class="container">
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>
</div>

app/views/notes/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Content:</strong>
  <p>
  <div style="font-size: large;">
    <%= raw sanitizing(@note.content) %>
  </div>
</p>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>
</div>