config/routes.rb
Rails.application.routes.draw do
  resources :notes
  get '/event_calendar/calendar/(:date)', to: 'event_calendar#calendar', as: 'event_calendar'
  get '/event_calendar/full_year_calendar/(:date)', to: 'event_calendar#full_year_calendar', as: 'full_year_calendar'

  resources :events
  devise_for :users
  root to: 'static_pages#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/event_calendar_controller.rb
class EventCalendarController < ApplicationController
  def calendar
    date = params[:date]
    if date.nil? || date.empty?
      @date = Date.today
    else
      @date = Date.parse(date)
    end

    only_month_days = @date.beginning_of_month..@date.end_of_month
    calendar_days = @date.beginning_of_month.beginning_of_week - 1.day..@date.end_of_month.end_of_week + 1.day
    @events = Event.where(starting: calendar_days).order(:starting)
  end

  def full_year_calendar
    date = params[:date]
    if date.nil? || date.empty?
      @date = Date.today
    else
      @date = Date.parse(date)
    end

    @events = Event.where(starting: @date.beginning_of_year..@date.end_of_year).order(:starting)
  end
end

app/helpers/event_calendar_helper.rb
module EventCalendarHelper
end

app/views/event_calendar/_calendar.html.erb
<% month = date.month %>
<% first_day = date.beginning_of_month.beginning_of_week %>
<% last_day = date.end_of_month.end_of_week %>
<% all_month_days = first_day..last_day %>
<% only_month_days = date.beginning_of_month..date.end_of_month %>

<!-- Month -->
<div class="container-fluid bg-white">
    <div class="jumbotron bg-white">
      <div class="text-center mb-4">
          <h3 class="text-h-color spaced-letters font-weight-light text-uppercase">Kalender</h3>
          <p>
            <%= link_to 'New Event', new_event_path %>
          </p>
          <p>
            <%#= link_to "Alle Events in deinen Kalender eintragen", events_icalendar_path, class: "btn btn-info"  %>
          </p>
      </div>
      <div class="text-center m-2">
        <%= link_to event_calendar_path(date - 1.month) do %>
          <div class="btn btn-primary">
            &#8249; &#8249;
          </div>
        <% end %>
        <span class="mx-3">
          <b><%= I18n.t("date.month_names")[month] %> <%= date.year %></b>
        </span>
        <%= link_to event_calendar_path(date + 1.month) do %>
          <div class="btn btn-primary">
            &#8250; &#8250;
          </div>
        <% end %>
      </div>

      <div class="">
        <table class="table table-bordered rounded">
        <thead>
          <tr>
            <th class="text-center small-text">Montag</th>
            <th class="text-center small-text">Dienstag</th>
            <th class="text-center small-text">Mittwoch</th>
            <th class="text-center small-text">Donnerstag</th>
            <th class="text-center small-text">Freitag</th>
            <th class="text-center small-text">Samstag</th>
            <th class="text-center small-text">Sonntag</th>
          </tr>
        </thead>
        <tbody>
          <% all_month_days.to_a.in_groups_of(7).each do |week| %>
            <tr style="height: 150px;">
              <% week.each do |day| %>
              <% backgroundcolorforday = "bg-lightgray" unless day.between?(date.beginning_of_month, date.end_of_month) %>
              <% backgroundcolorforday = "bg-lightcyan" if day === Date.today %>
              <td class="day-td <%= day.strftime("%d-%m-%Y") %> <%= backgroundcolorforday %>" style="width: 14.28%;">
                <%= render "event_calendar/day-lg", day: day, events: events %>
              </td>
              <% end %>
            </tr>
          <% end %>

        </tbody>
      </table>
    </div>

  </div>

  <%= render "events/event_list", events: events, date: date %>



</div>

app/views/event_calendar/_day-lg.html.erb
<div class="float-right small-text"><small><%= day.strftime("%-d") %></small></div>
<br>
<%# events = events.where(start_of_date: day)%>
<% events = events.between(day.beginning_of_day, day.end_of_day)%>
<%# events = Event.all %>
<% events.each do |event| %>

    <div class="border border-info rounded text-white bg-info w-100 p-1 trigger-hover-div-for-event mb-1" data-event-id="<%= event.id %>">
      <small>
        <%= event.starting.strftime("%H:%M") %> - <%= event.ending.strftime("%H:%M") %>
      </small>
      <br />
      <%= link_to event.title, event_path(event), class: "text-white" %>
    </div>

<% end %>
<hr />
<%= link_to 'New Event', new_event_path(starting: day.beginning_of_day, ending: day.beginning_of_day) %>
<%#= render 'events/form', event: Event.new(starting: day.beginning_of_day, ending: day.beginning_of_day) %>

app/views/event_calendar/_full_year_calendar.html.erb
<% month = date.month %>
<% first_day = date.beginning_of_month.beginning_of_week %>
<% last_day = date.end_of_month.end_of_week %>
<% all_month_days = first_day..last_day %>
<% only_month_days = date.beginning_of_month..date.end_of_month %>

<!-- Month -->
<div class="container-fluid bg-white">
    <div class="jumbotron bg-white">
      <div class="text-center mb-4">
          <h3 class="text-h-color spaced-letters font-weight-light text-uppercase">Kalender</h3>
          <p>
            <%= link_to 'New Event', new_event_path %>
          </p>
          <p>
            <%#= link_to "Alle Events in deinen Kalender eintragen", events_icalendar_path, class: "btn btn-info"  %>
          </p>
      </div>
      <div class="text-center m-2">
        <%= link_to event_calendar_path(date - 1.month) do %>
          <div class="btn btn-primary">
            &#8249; &#8249;
          </div>
        <% end %>
        <span class="mx-3">
          <b><%= I18n.t("date.month_names")[month] %> <%= date.year %></b>
        </span>
        <%= link_to event_calendar_path(date + 1.month) do %>
          <div class="btn btn-primary">
            &#8250; &#8250;
          </div>
        <% end %>
      </div>

      <div class="">
        <table class="table table-bordered rounded">
        <thead>
          <tr>
            <th class="text-center small-text">Montag</th>
            <th class="text-center small-text">Dienstag</th>
            <th class="text-center small-text">Mittwoch</th>
            <th class="text-center small-text">Donnerstag</th>
            <th class="text-center small-text">Freitag</th>
            <th class="text-center small-text">Samstag</th>
            <th class="text-center small-text">Sonntag</th>
          </tr>
        </thead>
        <tbody>
          <% all_month_days.to_a.in_groups_of(7).each do |week| %>
            <tr style="height: 150px;">
              <% week.each do |day| %>
              <% backgroundcolorforday = "bg-lightgray" unless day.between?(date.beginning_of_month, date.end_of_month) %>
              <% backgroundcolorforday = "bg-lightcyan" if day === Date.today %>
              <td class="day-td <%= day.strftime("%d-%m-%Y") %> <%= backgroundcolorforday %>" style="width: 14.28%;">
                <%= render "event_calendar/day-lg", day: day, events: events %>
              </td>
              <% end %>
            </tr>
          <% end %>

        </tbody>
      </table>
    </div>

  </div>

  <%= render "events/event_list", events: events, date: date %>



</div>

app/views/event_calendar/calendar.html.erb
<%= render "event_calendar/calendar", events: @events, date: @date %>

app/views/event_calendar/full_year_calendar.html.erb
<%= render "event_calendar/calendar", events: @events, date: @date %>